units:
  kx: U
  ky: U
  px: kx + 4
  py: ky + 4
  dpx: kx + 6
  dpy: ky + 6
# M2 Screw Inserts
  screwSize: 1.5
  standoffSize: 2.5
points:
  zones:
    matrix:
      anchor:
        shift: [100, -100]
      key:
        padding: ky
        spread: kx
      columns:
        pinky:
          rows:
            mod:
              skip: true
          key:
            column_net: P21
        ring:
          rows.mod.skip: true
          key:
            stagger: 5
            column_net: P20
        middle:
          key:
            stagger: 2.5
            column_net: P19
        index:
          key:
            stagger: -2.5
            column_net: P18
        inner:
          key:
            stagger: -2.5
            column_net: P15
      rows:
        bottom:
          row_net: P10
        home:
          row_net: P16
        top:
          row_net: P14

    thumbs:
      key:
        padding: py
        spread: px
      anchor:
        ref: matrix_inner_bottom
        shift: [-6, -py-2]
      columns:
        layer:
          key:
            splay: -15
            column_net: P19
        space:
          key:
            rotate: -115
            shift: [4,-2]
            width: 1.5kx
            column_net: P18
        extra:
          key:
            rotate: -120
            shift: [2,-12]
            width: 1.5kx
            column_net: P15
      rows:
        cluster:
          row_net: P6
outlines:
  raw:
    - what: rectangle
      where: true
      size: [px, py]
  keys:
    - what: rectangle
      where: true
      size: [kx-0.5,ky-0.5]
  switches:
    - what: rectangle
      where: true
      size: 14
  board:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_pinky_top
          shift: [-0.5px,0.5py]
        - ref: matrix_ring_top
          shift: [-0.5px,0.5py]
        - ref: matrix_middle_top
          shift: [-0.1px,0.6py]
        - ref: matrix_inner_top
          shift: [1.7px,0.4py]
        - ref: thumbs_space_cluster
          shift: [-0.8px,0.5py]
        - ref: thumbs_layer_cluster
          shift: [3px, -0.2py]
        - ref: thumbs_layer_cluster
          shift: [2.25px,-1.4py]
        - ref: thumbs_extra_cluster
          shift: [1.3px,-2.3py]
        - ref: matrix_index_bottom
          shift: [0.1px,-0.7py]
        - ref: matrix_pinky_bottom
          shift: [-0.5px,-0.5py]
      fillet: 4
  xlBoard:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_pinky_top
          shift: [-0.5dpx,0.5dpy]
        - ref: matrix_ring_top
          shift: [-0.5dpx,0.5dpy]
        - ref: matrix_middle_top
          shift: [-0.1dpx,0.6dpy]
        - ref: matrix_inner_top
          shift: [1.7dpx,0.4dpy]
        - ref: thumbs_space_cluster
          shift: [-0.8dpx,0.5dpy]
        - ref: thumbs_layer_cluster
          shift: [2.9dpx, -0.2dpy]
        - ref: thumbs_layer_cluster
          shift: [2.1dpx,-1.4dpy]
        - ref: thumbs_extra_cluster
          shift: [1.3dpx,-2.15dpy]
        - ref: matrix_index_bottom
          shift: [0,-0.7dpy]
        - ref: matrix_pinky_bottom
          shift: [-0.5dpx,-0.5dpy]
      fillet: 4
  _extraArea:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_inner_top
          shift: [0.53kx,0.6dpy]
        - ref: matrix_inner_bottom
          shift: [0.53kx,-0.5kx]
        - ref: thumbs_extra_cluster
          shift: [-1dpx,dpy]
        - ref: matrix_inner_top
          shift: [2.5kx,0.4dpy]
  _wallOpening:
    - what: rectangle
      where: matrix_inner_home
      adjust:
        - shift: [px,0.5px+20]
      size: [7.7, 4]
  _wallOpeningFillUsb:
    - what: rectangle
      where: matrix_inner_home
      adjust:
        - shift: [px,0.5px+19.3]
        - rotate: -6
      size: [7.7, 1.2]
  combo:
    - name: board
    - operation: subtract
      name: keys
  switchPlate:
    - name: board
    - operation: subtract
      name: switches
  _finalMount:
    - name: switchPlate
    - operation: subtract
      name: _extraArea
  mounting:
    - what: circle
      radius: screwSize
      where:
        ref: [matrix_pinky_top]
        shift: [0.5kx, -0.3ky]
    - what: circle
      radius: screwSize
      where:
        ref: [matrix_index_top]
        shift: [0.5kx, -0.3ky]
    - what: circle
      radius: screwSize
      where:
        ref: [matrix_pinky_bottom]
        shift: [0.5kx, 0.7ky]
    - what: circle
      radius: screwSize
      where:
        ref: [thumbs_layer_cluster]
        shift: [0.7kx, 0.3ky]
    - what: circle
      radius: screwSize
      where:
        ref: [thumbs_extra_cluster]
        shift: [0, -0.5ky]
    - what: circle
      radius: screwSize
      where:
        ref: [matrix_index_bottom]
        shift: [0.5kx, 0.5ky]
  standoff:
    - what: circle
      radius: standoffSize
      where:
        ref: [matrix_pinky_top]
        shift: [0.5kx, -0.3ky]
    - what: circle
      radius: standoffSize
      where:
        ref: [matrix_index_top]
        shift: [0.5kx, -0.3ky]
    - what: circle
      radius: standoffSize
      where:
        ref: [matrix_pinky_bottom]
        shift: [0.5kx, 0.7ky]
    - what: circle
      radius: standoffSize
      where:
        ref: [thumbs_layer_cluster]
        shift: [0.7kx, 0.3ky]
    - what: circle
      radius: standoffSize
      where:
        ref: [thumbs_extra_cluster]
        shift: [0, -0.5ky]
    - what: circle
      radius: standoffSize
      where:
        ref: [matrix_index_bottom]
        shift: [0.5kx, 0.5ky]
pcbs:
  juubo_left:
    outlines:
      main:
        outline: board
    footprints:
      rotary:
        what: rotary
        where: 
          ref: 
            - matrix_inner_bottom
          shift: [px, -0.2px]
        params:
          from: P9
          to: GND
          A: P7
          B: P8
          C: GND
      mx_hotswap:
        what: mx
        where: true
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
      promicro:
        what: promicro
        params:
          orientation: "down"
        where:
          ref: matrix_inner_home
          shift: [px,0.5px]
          rotate: -90
      onOff:
        what: slider
        params:
          side: 'B'
          from: RAW
          to: B+
        where:
          ref: matrix_inner_top
          shift: [px,0.39px]
      jst:
        what: jstph
        params:
          side: 'F'
          pos: B+
          neg: GND
        where:
          ref: matrix_inner_home
          shift: [px,-0.55py]
        adjust:
          rotate: 180
      resistor:
        what: resistor
        where:
          ref: matrix_inner_home
        params:
          side: 'B'
          PAD1: VCC
          PAD2: P3
        adjust:
          shift: [1.75kx, -6]
          rotate: -90
      resistor2:
        what: resistor
        where:
          ref: matrix_inner_home
        params:
          side: 'B'
          PAD1: VCC
          PAD2: P2
        adjust:
          shift: [1.65kx, -6]
          rotate: -90
      reset:
        what: button
        params:
          from: GND
          to: RST
        where:
          ref: 
            - matrix_inner_bottom
          shift: [1.55px, 1.8px]
          rotate: 90
      trrs:
        what: trrs
        params:
          A: VCC
          B: P3
          C: P2
          D: GND
        where:
          ref: 
            - matrix_inner_bottom
          shift: [1.7px, 0.25px]
          rotate: -90
      holeTopLeft:
        what: mountinghole
        where:
          ref: [matrix_pinky_top]
          shift: [0.5kx, -0.3ky]
      holeTopInner:
        what: mountinghole
        where:
          ref: [matrix_index_top]
          shift: [0.5kx, -0.3ky]
      holeBottomLeft:
        what: mountinghole
        where:
          ref: [matrix_pinky_bottom]
          shift: [0.5kx, 0.7ky]
      holeThumbLeft:
        what: mountinghole
        where:
          ref: [thumbs_layer_cluster]
          shift: [0.7kx, 0.3ky]
      holeThumbsRoght:
        what: mountinghole
        where:
          ref: [thumbs_extra_cluster]
          shift: [0, -0.5ky]
      holeInnerBottomRight:
        what: mountinghole
        where:
          ref: [matrix_index_bottom]
          shift: [0.5kx, 0.5ky]
  juubo_left_plate:
    outlines:
      main:
        outline: _finalMount
    footprints:
      holeTopLeft:
        what: mountinghole
        where:
          ref: [matrix_pinky_top]
          shift: [0.5kx, -0.3ky]
      holeTopInner:
        what: mountinghole
        where:
          ref: [matrix_index_top]
          shift: [0.5kx, -0.3ky]
      holeBottomLeft:
        what: mountinghole
        where:
          ref: [matrix_pinky_bottom]
          shift: [0.5kx, 0.7ky]
      holeThumbLeft:
        what: mountinghole
        where:
          ref: [thumbs_layer_cluster]
          shift: [0.7kx, 0.3ky]
      holeThumbsRoght:
        what: mountinghole
        where:
          ref: [thumbs_extra_cluster]
          shift: [0, -0.5ky]
      holeInnerBottomRight:
        what: mountinghole
        where:
          ref: [matrix_index_bottom]
          shift: [0.5kx, 0.5ky]
cases:
  bottom:
    - name: board
      extrude: 1
  xlBottom:
    - name: xlBoard
      extrude: 1
  _outerWall:
    - name: xlBoard
      extrude: 7.2
  _innerWall:
    - name: board
      extrude: 7.2
  _opening:
    - name: _wallOpening
      extrude: 7.2
  _openingFill:
    - name: _wallOpeningFillUsb
      extrude: 2
  wall:
    - what: case
      name: _outerWall
      operation: add
    - what: case
      name: _innerWall
      operation: subtract
    - what: case
      name: _opening
      operation: subtract
    - what: case
      name: _openingFill
      operation: add
  _holes:
    - name: mounting
      extrude: 4
  _standoffs:
    - name: standoff
      extrude: 4
  case:
    - what: case
      name: _standoffs
      operation: add
    - what: case
      name: _holes
      operation: subtract
    - what: case
      name: xlBottom
      operation: add
    - what: case
      name: wall
      operation: add


