units:
  kx: U
  ky: U
  px: kx + 4
  py: ky + 4
points:
  zones:
    matrix:
      anchor:
        shift: [100, -100]
      key:
        padding: ky
        spread: kx
      columns:
        pinky:
          rows:
            mod:
              skip: true
          key:
            column_net: P18
        ring:
          rows.mod.skip: true
          key:
            stagger: 5
            column_net: P19
        middle:
          key:
            stagger: 2.5
            column_net: P20
        index:
          key:
            stagger: -2.5
            column_net: P21
        inner:
          key:
            stagger: -2.5
            column_net: P1
      rows:
        bottom:
          row_net: P16
        home:
          row_net: P14
        top:
          row_net: P15

    thumbs:
      key:
        padding: py
        spread: px
      anchor:
        ref: matrix_inner_bottom
        shift: [-6, -py-2]
      columns:
        layer:
          key:
            splay: -15
            column_net: P20
        space:
          key:
            rotate: -115
            shift: [4,-2]
            width: 1.5kx
            column_net: P21
        extra:
          key:
            rotate: -120
            shift: [2,-12]
            width: 1.5kx
            column_net: P1
      rows:
        cluster:
          row_net: P10
outlines:
  raw:
    - what: rectangle
      where: true
      size: [px, py]
  keys:
    - what: rectangle
      where: true
      size: [kx-0.5,ky-0.5]
  board:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_pinky_top
          shift: [-0.5px,0.5py]
        - ref: matrix_ring_top
          shift: [-0.5px,0.5py]
        - ref: matrix_middle_top
          shift: [-0.1kx,0.6py]
        - ref: matrix_inner_top
          shift: [1.7px,0.4py]
        - ref: thumbs_space_cluster
          shift: [-0.8px,0.5px]
        - ref: thumbs_layer_cluster
          shift: [3px, -0.2px]
        - ref: thumbs_layer_cluster
          shift: [2.25px,-1.4px]
        - ref: thumbs_extra_cluster
          shift: [1.3px,-2.3px]
        - ref: matrix_index_bottom
          shift: [0.1px,-0.7px]
        - ref: matrix_pinky_bottom
          shift: [-0.5px,-0.5px]
      fillet: 4
  combo:
    - name: board
    - operation: subtract
      name: keys
pcbs:
  juubo_left_no_res:
    outlines:
      main:
        outline: board
    footprints:
      rotary:
        what: rotary
        where: 
          ref: 
            - matrix_inner_bottom
          shift: [px, -0.2px]
        params:
          from: P9
          to: GND
          A: P7
          B: P8
          C: GND
      mx_hotswap:
        what: mx
        where: true
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
      promicro:
        what: promicro
        params:
          orientation: "down"
        where:
          ref: matrix_inner_home
          shift: [px,0.5px]
          rotate: -90
      reset:
        what: button
        params:
          from: GND
          to: RST
        where:
          ref: 
            - matrix_inner_bottom
          shift: [1.55px, 1.8px]
          rotate: 90
      trrs:
        what: trrs
        params:
          A: VCC
          B: P2
          C: P3
          D: GND
        where:
          ref: 
            - matrix_inner_bottom
          shift: [1.7px, 0.3px]
          rotate: -90


